### ISSUE TITLE
Determine what ATO we need (and get the ball rolling)

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#10]
Preauthorization ATO or 90 Day ATO

https://pages.18f.gov/before-you-ship/

**Comment by fureigh** [comment]
Preauth is good to start! Let's look into https://pages.18f.gov/before-you-ship/ato/types/#day-authorization.

**Comment by porta-antiporta** [comment]
for viz, here's the current draft #infrstructure issue tracking L-ATO for our alpha: https://github.com/18F/Infrastructure/issues/704

**Comment by fureigh** [comment]
Confirming: we should be good to go with a pre-authorization, as we'll:
1. Design the system in such a way that it doesn't store any PII (for this prototype, at least),
2. Deploy to cloud.gov, and
3. Set up HTTP Basic Authentication.

**Comment by fureigh** [comment]
Closing this ticket, as the decision is complete and the resulting actions have their own tickets.
