### ISSUE TITLE
Write form-field copy for N-400 prototype

### ISSUE THREAD

**Issue by kategarklavs** [18F/ffd-info-exchange#100]
Based on the inventory of form fields on the N-400/PreCheck app/passport app, I'll write form fields for our N-400 prototype.

Specific steps:

- [x] Write initial draft
- [x] Discuss with @donjo @fureigh & team to identify areas that require more attention
- [x] Publish!

**Comment by kategarklavs** [comment]
Initial draft done and shared with the team 🎉

**Comment by kategarklavs** [comment]
Update: @fureigh made comments/suggestions to the first draft yesterday (and many thanks!), and I'll reach out to @donjo to see if he has specific recommended changes.

**Comment by kategarklavs** [comment]
Copy is being added to the prototype as we speak 🎉 I'll revise/reconfigure the copy once it's in the prototype — closing this issue for now.

**Comment by fureigh** [comment]
Here's the [living draft](https://docs.google.com/document/d/1o0n3NOG0uLzQtnCiUwqG5lhWWn4JoYgYruFOPzzXCvk/edit#). Thanks, @kategarklavs!

**Comment by kategarklavs** [comment]
@fureigh Thanks for adding the link!
