### ISSUE TITLE
Implement progress tracker

### ISSUE THREAD

**Issue by fureigh** [18F/ffd-info-exchange#103]
**Technical notes:**
'Pizza tracker,' based on USCIS mockups.

**Comment by fureigh** [comment]
We do already have 'Step X of Y', though. @donjo?

**Comment by donjo** [comment]
I'm inclined to just stick with the Step X of Y type thing for now. I haven't quite figured out how to handle this in the bonus services section. I think the steps counted should probably just be N-400 steps and then we will do something else (or nothing at all) for the bonuses. Maybe Step X of Y where Y is dynamic based on the number of services you selected to apply for?

**Comment by kategarklavs** [comment]
+1 to _Step X of Y_. Re: bonus steps: @donjo, I'm inclined to agree with the _do nothing_ stance — to include those in the total # of steps could presume that folks should choose one or more of the add-ons (whereas it's totally fine if people opt not to go w/any of the add ons).

**Comment by fureigh** [comment]
:100: to all of the above. #131 is the ticket for restricting the number of steps to the N-400 steps. Closing this ticket. :tada:
