### ISSUE TITLE
Write up findings from this phase

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#111]
To aid our partners in contacting agencies in the next quarter we shall write up the findings from this phase into a document that can be given to a potential partner agency.

**Comment by kategarklavs** [comment]
@porta-antiporta Is this separate from our final report? (My initial thought is that the document mentioned in this issue could be a one sheet, but I'm open to other options, too.)

**Comment by porta-antiporta** [comment]
@kategarklavs This is the epic that captures all our efforts to write up (and therefor wrap up) our work for this engagement.  So it includes creation of the final report.  (Though noticed there's no story within this epic for writing up the final report so I'll create that and assign to you).

**Comment by kategarklavs** [comment]
@porta-antiporta Sounds good re: the report issue. Aside from the standard sprint summary in the wiki, are there other types of writing you're thinking of? (I can then go ahead and open issues for those deliverables, as well.)

**Comment by porta-antiporta** [comment]
@kategarklavs I was looking to have a single report that covers all our sprints in a single report (format is up to us).  I opened #126 to capture that request.

**Comment by kategarklavs** [comment]
Sounds good! I'll create an issue for our final wiki sprint summary, and we should be all set.
