### ISSUE TITLE
Write up of Sprint 4 work

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#113]
Update wiki to include our work for Sprint 4.

Some subtasks:

- [x] Create initial draft
- [x] Share w/team to make sure the account is complete
- [x] Publish!

**Comment by kategarklavs** [comment]
Steps one and two are done — just waiting for team feedback now.

**Comment by kategarklavs** [comment]
Thanks to all the folks who left feedback! This summary is now up on the wiki. 🎉
