### ISSUE TITLE
Create script for prototype 2 testing

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#115]
We will be testing prototype 2 with users Dec 19-21.
Create the script that will be used during that testing.

Testing will be:
* Remote (participant in Chicago office, but facilitators potentially remote)
* 1 hour long

Hypotheses we wanted tested were:
@donjo @kategarklavs @fureigh could one of you link the hypotheses doc to this story please?

To-dos:

- [x] Create complete first draft of script
- [x] Share draft with team (feedback)
- [x] Once prototype is finalized, update the script, as appropriate

**Comment by kategarklavs** [comment]
This issue is in progress (script is currently about half done).

And here's the hypotheses doc:

https://docs.google.com/a/gsa.gov/document/d/11VvgpgJofKa_wHda1M5nKxV7i3yTNCgKtAsJNjPtxnw/edit?usp=sharing

**Comment by porta-antiporta** [comment]
Target a test run during this sprint.

**Comment by kategarklavs** [comment]
Update: Script draft is about 2/3 complete (document is here: https://docs.google.com/a/gsa.gov/document/d/1nim5aGmDE4vwkgUIJK97PkHjZuvJJMe70M1nLFt0bMc/edit?usp=sharing).

Aiming to have the draft wrapped up & shared with the team by EOD. Script will necessarily change based on updates to the prototype, but this will be a good foundation.

**Comment by kategarklavs** [comment]
Just finished draft 1 of the script and shared it with the team/asked for feedback.

**Comment by kategarklavs** [comment]
Update: A number of people have shared feedback on the script (thank you!), and the script is in good shape. Still waiting for finalization of the prototype, after which I'll make another round of edits to the script.

**Comment by kategarklavs** [comment]
Shared the script at today's demo, and everything should be set!

Per this morning's demo discussion, I added passport + TSA PreCheck/Global Entry cost information to the script (should participants have questions about fees). I also added standard definitions of these services — in the case that participants aren't familiar with these services, the moderator can offer succinct descriptions.

Going to close this issue for now, but feel free to reopen if you have questions/certain aspects of the script need modification.
