### ISSUE TITLE
Create document describing participant recruitment process

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#117]

**Comment by kategarklavs** [comment]
@porta-antiporta Howdy! If you'd like any help with this, let me know -- happy to lend a hand.

**Comment by porta-antiporta** [comment]
@kategarklavs a hand would be greatly appreciated!

here's what i have so far:  https://docs.google.com/document/d/1ta44zN4m-kFsfXBMyql017zmNUWmVHKmoUWvFP6LL_E/edit#

**Comment by kategarklavs** [comment]
@porta-antiporta Excellent! I'll take a look at the current draft and then DM you so we can discuss the best approach 🎉

**Comment by kategarklavs** [comment]
@porta-antiporta Howdy! I made some edits/suggestions (and left some questions) in the document this afternoon. I'm happy to take another pass at it later on, as well: let me know if/when you'd like another set of eyes on it.

**Comment by porta-antiporta** [comment]
Complete and handed off to #research.  https://drive.google.com/drive/folders/0B8u6AetkKiTUeWhvOVFkZG5WSzQ
