### ISSUE TITLE
Communications

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#12]
recap of discussion with @kategarklavs.

We will keep a running journal (entries at the end of each sprint) to capture highlights, lowlights of each sprint.  This journal will be on the wiki so that there is a readily available artifact describing the progress we are making.

This journal can also be the basis for any additional communication that would need additional polish (newsletters, email updates etc).

**Comment by kategarklavs** [comment]
I've added a few related issues & will keep adding issues (and linking to this one) as new comms opportunities present themselves.

**Comment by porta-antiporta** [comment]
project is concluded, closing epic
