### ISSUE TITLE
Create final report on our findings

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#126]
Create a report that describes the project which includes:
* Methodology / Process
* Findings across agency and user research
* Recommendations for next steps

Format of this document can be a Google doc / slide.  Pure wiki may not be the best format if there is sensitive information.

**Comment by kategarklavs** [comment]
Outline lives here: https://docs.google.com/a/gsa.gov/document/d/1rKQViNUZhuHTnVsyZ93pY-mPvBcnByI89GpEYWiXE-s/edit?usp=sharing

(Note: None of the text in this document is anywhere close to finalized! In other words, this is the very beginning of a very rough draft 😎 Will let folks know when the text is ready for review/feedback.)

**Comment by kategarklavs** [comment]
An update on the report: Made some good progress this week (and thank you to folks for their feedback!). 

Right now, the report has a solid intro, executive summary, end-user research section, and preliminary findings. Agency research section is still in progress. We won't be able to finish the exec summary, findings, and potential next steps until after we complete next week's round of research.

**Comment by porta-antiporta** [comment]
Report has been delivered to OPP.  Closing this one but leaving #169 as open to see if we will publish the report to "somewhere other than g-drive"
