### ISSUE TITLE
Blog post

### ISSUE THREAD

**Issue by kategarklavs** [18F/ffd-info-exchange#127]
If time allows, let's write a blog post detailing our more surprising findings + their implications for future infosharing research.

- [x] Create issue in blog-drafts repo
- [ ] First draft
- [ ] Share draft with team for feedback
- [ ] Revise, as necessary
- [ ] Submit to blog team for review/approval process

**Comment by porta-antiporta** [comment]
Given current comms approval process and folks have transitioned off; closing this issue.
