### ISSUE TITLE
Design spike: define high level approach/architecture for alpha

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#14]
Developers to define and align on architecture for Alpha:

Some items to consider:
- What infosec concerns should we be particularly conscious of
- If proceeding with an enterprise service bus approach (as we do not want to store data), how will we mock the agency endpoints?  Do we need to understand their technical stack/constraints?
- What metrics do we want to keep track of that are NOT default included in Google Analytics

At the end of this story want to have:
- [ ] Alignment with @jpyuda that approach is viable
- [ ] High level architecture diagram (to guide implementation and comms)
- [ ] Completed review @jacobian of infosec concerns and any ongoing tests that should be built in
- [ ] Worked with @porta-antiporta on creating next stories to be worked on

**Comment by fureigh** [comment]
As part of this, let's get clear on high-level user stories and center those.

**Comment by porta-antiporta** [comment]
David Simeon, Yemi Oshinnaiye from USCIS would be good contacts so understand architecutre requirements (after login.gov ships)

**Comment by porta-antiporta** [comment]
@fureigh now that we have a tighter direction, any objections to closing this story and opening a new one(s)?

#26
#29

**Comment by fureigh** [comment]
@porta-antiporta No objections... I'll make new tickets to account for convos still to happen with @jacobian, etc.
