### ISSUE TITLE
Finish migrating the Labs project

### ISSUE THREAD

**Issue by fureigh** [18F/ffd-info-exchange#171]
:)

**Comment by donjo** [comment]
Things to do 

- [x] migrate production to GovCloud
- [x] set up automated deployment

**Comment by fureigh** [comment]
@donjo Did https://github.com/18F/ffd-microsite/pull/60 and https://github.com/18F/ffd-microsite/pull/61 close this?

**Comment by donjo** [comment]
@fureigh updating checkboxes. First item is resolved. Second item will be resolved in 18F/ffd-microsite#62

**Comment by donjo** [comment]
migration complete and automated deployment set up successfully in 18f/ffd-microsite#63

last thing to do is get the labs.usa.gov domain pointing to the right spot

**Comment by fureigh** [comment]
@donjo Following up, as yesterday was the deadline for migration to GovCloud: has this been completed? Is it safe to delete everything from the original hosting environment?

(cc @jcscottiii)

**Comment by donjo** [comment]
@fureigh yep. all done

**Comment by porta-antiporta** [comment]
for posterity: relevant slack thread: https://gsa-tts.slack.com/archives/ffd-info-exchange/p1484759667001593

**Comment by fureigh** [comment]
@donjo @porta-antiporta Thanks!

**Comment by jcscottiii** [comment]
Deleted the old org!

**Comment by porta-antiporta** [comment]
verified that going to labs.usa.gov we are still seeing the site.  (layman's confirmation that we are definitely operating out of GovCloud now).
