### ISSUE TITLE
Research: interface language involving high stakes sharing

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#18]
Research sites, products that involve users needing to authorize sharing of information and synthesize findings into a list of patterns that should inform the design for our prototype

**Comment by porta-antiporta** [comment]
Current notes doc: https://docs.google.com/document/d/1U2CMuAf39ATlJY3__4VljfvIhVKc60sQXU4c-Hqm8iM/edit

**Comment by kategarklavs** [comment]
An update: Yesterday, I did a small bit more research and then summarized my findings in this doc:

https://docs.google.com/document/d/1Og4rZOgn8-RteMEBOMn3CuL32VrFOkOQBL_JkynBN7s/edit#

During today's standup, will check in with the team to find out whether we'd like to add this doc to our wiki, or whether we'd rather just keep it in Drive.

**Comment by kategarklavs** [comment]
OK! After opening this question in the channel, the team decided that we can keep the synthesis doc in drive and reference it in our wiki. My plan is to reference this doc in the hypotheses/ideal test cases doc @cydharrell and I are working on. 

For now, going to close this issue, but I'm happy to reopen if folks would like me to conduct additional research.
