### ISSUE TITLE
Investigate & create copy for privacy notices

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#19]
As we prepare for building the prototype, we will likely have to have privacy notices within the user experience.

This story will define that content and align with UX to determine how that content should be presented.

We may need to test multiple copy/prototypes around this.

**Comment by kategarklavs** [comment]
Starting to research different organizations' privacy notices + best practices; once I start writing sample notices, I'll post a link to the doc here.

**Comment by kategarklavs** [comment]
A quick update: I touched base with @donjo yesterday, and he should have prototype designs soon, at which point I'll begin adding copy (including privacy notices).

**Comment by kategarklavs** [comment]
Ack! I thought I'd shared this link on GH, but it turns out I'd only shared it with individual ppl on the team :/

In any event, here's the doc with observations/thoughts on privacy notices: 

https://docs.google.com/document/d/16R0VMGOs_dI2jt4giaj_fCNrtKEvM47XgpD5QTVIpL8/edit

**Comment by kategarklavs** [comment]
Today, started drafting some page-specific help text and privacy notices for our prototype. **Note**: this is by no means complete! But I wanted to share what I'd done so far: 

https://docs.google.com/document/d/1abLfJxXFIqDAfw9a8Y6B7b7mQvCYzgRFY7SM1GnmFpk/edit#

**Comment by kategarklavs** [comment]
As we discussed in our demo/retro meeting of 11/4/16, we're going to create a separate issue for integrating the privacy notices into the prototype — closing this issue!
