### ISSUE TITLE
Publish our ideal test cases and hypotheses into the repo's wiki

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#22]
1. a good test case involves data that is some level of burden to replicate
2. a good test case involves data that is directly used in some determination that an agency makes (edited)
3. a good test case involves something that users view as a single task
4. a good test case _probably_ doesn't involve law enforcement data, because a lot of the Privacy Act exceptions and Exemptions are in that area
5. a good test case involves data that users wouldn't share with just anyone
6. a good test case involves data that has an accepted canonical source agency in government

**Comment by kategarklavs** [comment]
Status update: @cydharrell and I are currently working on this document:

https://docs.google.com/a/gsa.gov/document/d/1A2bNu1mZapGpHNOTboK_z3m3mGszmrdmjJ2UNXeweJ4/edit?usp=sharing

**Comment by kategarklavs** [comment]
Update: Just replied to some comments on this document (and am awaiting responses). My goal is to have the document in its final form, edited, and published today — tomorrow might be more realistic, though. Will post more updates as I have them!

**Comment by kategarklavs** [comment]
OK — just published this document to the wiki and shared it in our channel. As we refine our hypotheses, we can update the page. 

Going to close this issue for now, but please feel free to re-open if you feel we should revisit it.
