### ISSUE TITLE
Create about.yml and update readme per ATO checklist.

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#25]
As part of the ATO checklist, our repo should include certain artifacts describing the scope of our project.

Doing the following:
- [ ] add about.yml file
- [x] update readme with description of the project

**Comment by porta-antiporta** [comment]
@kategarklavs finished the update to the readme file.

**Comment by kategarklavs** [comment]
@porta-antiporta Howdy! I've never created an about.yml file before, but am happy to pair with someone on it (or proofread the completed file, if someone else would rather write it) — which approach would make the most sense?

**Comment by porta-antiporta** [comment]
@kategarklavs happy to pair with you on it!  the template about.yml file is here:
https://github.com/18F/about_yml/blob/master/.about.yml  i haven't yet created it in our repo.

**Comment by kategarklavs** [comment]
@porta-antiporta Sounds good! I'll take a look at the template now :)
