### ISSUE TITLE
Scaffold out a placeholder form

### ISSUE THREAD

**Issue by fureigh** [18F/ffd-info-exchange#26]
**Why:**
- One way or another, it's likely that we'll present a form to users (for testing hypotheses and otherwise), so let's build something basic that can be modified as necessary.
- Might as well get started! :)

**Comment by fureigh** [comment]
- [ ] USA.gov branding

**Comment by fureigh** [comment]
We have no need for the data itself at this time, correct? Assuming that's the case, I'll plan to disable the Submit button for now (at least) to prevent the system from storing any PII.

**Comment by kategarklavs** [comment]
@fureigh Whenever you're ready for content, lmk!

**Comment by fureigh** [comment]
@kategarklavs Ready!

**Comment by kategarklavs** [comment]
@fureigh Excellent! Can you share a link to said form? (It's entirely likely that I've overlooked a link :/ )

**Comment by fureigh** [comment]
@kategarklavs WIP in https://github.com/18F/ffd-info-exchange/pull/46! Aiming to deploy to cloud.gov tomorrow, adding more fields first.

**Comment by kategarklavs** [comment]
@fureigh Excellent! Should I keep editing in the Drive Doc, or elsewhere? (I've been making tiny tiny changes to some of the form language, but can definitely hold off if editing in the Drive Doc will cause unnecessary work)

**Comment by fureigh** [comment]
@kategarklavs Drive's good for now, thanks! I'll refactor this soon in such a way that you'll be able to make copy changes in the code without having to mess with migrations.

**Comment by kategarklavs** [comment]
@fureigh That sounds excellent! (And if I have any process questions, I'll ping you right away.)

**Comment by fureigh** [comment]
@kategarklavs Pending review in https://github.com/18F/ffd-info-exchange/pull/48. Once that's in, we can :pear: on it if useful. Adding more fields in the meantime...

**Comment by donjo** [comment]
I suppose this one is done now since it was prototype 1 related.
