### ISSUE TITLE
Create first prototype based off FAFSA/IRS integration

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#29]
As part of #15 we will have our first design for our prototype.
Build out the form so we have our first implementation that can be tested.

**Comment by fureigh** [comment]
@porta-antiporta This appears to be a duplicate of #26 that adds a definition of done ("can be tested"). If that's accurate, mind if I close this one? I can go either way on it but I've already attached commits to the other one.

**Comment by porta-antiporta** [comment]
@fureigh sure thing.

**Comment by porta-antiporta** [comment]
duplicate of #26
