### ISSUE TITLE
Recruit users for testing

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#32]
- [ ] Micropurchase
- [ ] Ethn.io?

**Comment by porta-antiporta** [comment]
Discussed with @donjo and Liz various approaches to recruit users.
We will pursue a p-card purchase.
- [ ] Generate list of vendors
- [ ] Create profile of desired users
- [ ] Get approval from PO for purchase
- [ ] Get quote from vendors
- [ ] Select vendor
- [ ] Submit C2 request with NTE invoice amount
- [ ] Schedule date and travel (target before Thanksgiving)

@porta-antiporta to document for posterity

**Comment by fureigh** [comment]
@porta-antiporta This can be closed, yes?

**Comment by donjo** [comment]
For history's sake: Ultimately we chose the route of getting quotes from a handful of vendors and selected one to recruit our participants and schedule a week of testing in the SF Bay Area.
