### ISSUE TITLE
Deploy app-in-progress to cloud.gov

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#33]
- [ ] Finalize URL
- [ ] Deployment scripts or documentation
- [ ] Enables ATO activities
  - [ ] Monitoring
  - [ ] Dynamic scanning

**Comment by fureigh** [comment]
Let's start with `ffd-info-exchange-fafsa` — it's clunkily long, but self-documenting.

**Comment by fureigh** [comment]
@porta-antiporta I'd been assuming this issue was for deploying the app-in-progress to cloud.gov. Is that accurate or is it truly meant to be a dummy app?

**Comment by porta-antiporta** [comment]
@fureigh app-in-progress is a-OK (better than a dummy app).  When i wrote the story originally, was unsure what app development would have already taken place.  The main goal was that we have deployment kinks worked out.

**Comment by fureigh** [comment]
(Thanks @donjo!)

**Comment by fureigh** [comment]
#51 is a start.

**Comment by fureigh** [comment]
Moving this to sprint 6. Rationale: we don't need this for next week's testing, but doing it before the end of this engagement may support future conversations with agencies.

**Comment by porta-antiporta** [comment]
Putting this in the icebox.

**Comment by fureigh** [comment]
Sounds like we're scrapping this one in favor of leaving 1) a codebase with clear deployment instructions and 2) more specific representation in the report (screenshot snippets, animated GIFs, whatever works).
