### ISSUE TITLE
Create content testing script/questions

### ISSUE THREAD

**Issue by kategarklavs** [18F/ffd-info-exchange#39]
Our prototype usability tests should include tests that assess the effectiveness of the written content. I'll work with @cydharrell and @donjo to incorporate content-specific questions into our test scripts.

To-dos:
- [x] Draft questions
- [ ] Get feedback from team
- [ ] Incorporate into script

(And modify said questions, as needed)

**Comment by kategarklavs** [comment]
Here's the document in which I outline different (possible) content testing methods:

https://docs.google.com/document/d/10niKUvtPGAGcciMAaB3DsIUrfm2yxNC3m-TySV3Hw1A/edit#

Just pinged the team for feedback. As soon as I hear back from folks, I'll update the document and then close this issue.

**Comment by porta-antiporta** [comment]
Closing. We will finalize as part of #67
