### ISSUE TITLE
Internal newsletter blurb(s)

### ISSUE THREAD

**Issue by kategarklavs** [18F/ffd-info-exchange#40]
As we reach project milestones, we should communicate these to the larger 18F team, helping folks stay up-to-date on our progress. 

To-dos:
- [ ] Draft blurb(s) for the internal newsletter
- [ ] Share with team so folks can offer feedback
- [ ] Send to Andre for publication
- [ ] Repeat, as necessary

This relates to Epic #12

**Comment by porta-antiporta** [comment]
think this can be closed @kategarklavs ?  we somewhat tackled this via our wiki updates right?

**Comment by kategarklavs** [comment]
@porta-antiporta Howdy! Yes, I think this can be closed — we can direct folks to our wiki as we present our research (during All Hands, design huddle, etc.). Closing now.
