### ISSUE TITLE
Blog post

### ISSUE THREAD

**Issue by kategarklavs** [18F/ffd-info-exchange#41]
In addition to internal comms efforts (blurbs in the 18F internal newsletter, project-work updates at all hands, etc.), we should also consider external comms efforts.

Once we've completed our work (or near the end of the project), we can publish a blog post summarizing our work and highlighting major lessons learned. Exact topics TBD, as we're still working.

To-dos:
- [ ] Create issue in blog-drafts repo
- [ ] Draft blog post
- [ ] Share with team / gather team feedback
- [ ] Submit post to blog team for review/approval 

This issue is related to the Epic #12

**Comment by porta-antiporta** [comment]
duplicate of #127
