### ISSUE TITLE
Prototype an outline of the FAFSA site that will contain form content

### ISSUE THREAD

**Issue by donjo** [18F/ffd-info-exchange#42]
Things to include in the base design: 
- Placeholder navigation (not to be used by the user but to make it feel like a real site) 
- Heading/subheading appropriate for the first page of the form

**Comment by fureigh** [comment]
What's the distinction between this and #26/#29?

**Comment by donjo** [comment]
There isn't any. I was translating issues I had written down on paper and didn't notice #29 was added yesterday morning. Closing this one out too.
