### ISSUE TITLE
Re-create one page worth of form content inside the prototype site

### ISSUE THREAD

**Issue by donjo** [18F/ffd-info-exchange#43]
The final form design may include a few different pages of content, separated by types of information being collected. However, we just need a few form fields here so we have a point of reference for discussions and engineering work.

**Comment by fureigh** [comment]
For #26/#29 I started working off of the [fields @kategarklavs listed from the FAFSA](https://docs.google.com/document/d/1d1LQ9_D-ATbkDGnCcmUS1cOkrjVypsl53fiBt5wwnok/edit)... which fields do you have in mind?

**Comment by donjo** [comment]
I was going to use the same fields. It sounds like this issue is redundant with what was described in the issues you linked.

**Comment by fureigh** [comment]
No problem! Just trying to make sure we're on the same page/issue.
