### ISSUE TITLE
Set up auth mechanism

### ISSUE THREAD

**Issue by fureigh** [18F/ffd-info-exchange#58]
**User story:**
As a developer, I want to have to log in before accessing the site-in-progress so I can be confident that access to the system is limited to authorized persons.

**Technical notes:**
* Set up either cloud.gov SSO or HTTP Basic Authentication, whichever's a lighter lift.
* This is required for compliance with our [pre-authorization](https://pages.18f.gov/before-you-ship/ato/types/#day-authorization). Further context: https://github.com/18F/ffd-info-exchange/issues/10#issuecomment-256449939

**Comment by fureigh** [comment]
@donjo @porta-antiporta Note that if the first round of testing happens on cloud.gov (rather than locally), this should be set up first.

**Comment by fureigh** [comment]
Moving this to sprint 6. Rationale: we don't need this for next week's testing, but doing it before the end of this engagement may support future conversations with agencies.

**Comment by porta-antiporta** [comment]
not needed
