### ISSUE TITLE
Troubleshoot radio button rendering

### ISSUE THREAD

**Issue by fureigh** [18F/ffd-info-exchange#60]
Part of #26.

**Comment by donjo** [comment]
I believe we ultimately changed this one to a different type of select (or it was part of the questions we removed)

**Comment by fureigh** [comment]
Confirming, I changed 'em to selects in https://github.com/18F/ffd-info-exchange/commit/6f32f75b74d6801425c006267721d59c09d99e1c as a temporary measure.

**Comment by fureigh** [comment]
Reopening as this is still relevant for prototype 2. (It's true that we could make them all selects, but it'll be a less-than-ideal user experience.)

**Comment by fureigh** [comment]
Closing for now, per #134.
