### ISSUE TITLE
Incorporate privacy notices into prototype

### ISSUE THREAD

**Issue by kategarklavs** [18F/ffd-info-exchange#65]
This is a continuation of the now-closed #19.

As appropriate, we'll add privacy notices to our FAFSA prototype. (And if we determine that the privacy notices don't quite mesh with the prototype or aren't necessary, we can close this issue.)

- [x] Draft copy available in the prototype
- [x] Finalized copy for the user testing
- [x] Folks leading the user research have the appropriate copy needed to answer the questions posed during the test aroud privacy notices

cc @donjo and @fureigh

**Comment by fureigh** [comment]
:tada:

One implementation note: #64 is a precursor to at least some of this ("draft copy available in the prototype").

**Comment by kategarklavs** [comment]
This is also done — closing now.
