### ISSUE TITLE
Mark fields 'not required' for purposes of user testing

### ISSUE THREAD

**Issue by fureigh** [18F/ffd-info-exchange#66]
**Immediate user story:**
* As a team member doing usability testing, I want to be able to skip screens without the applicant having to stop to fill in example information.

**Likely user story:**
* As an applicant, I want to be able to move on to answering other questions in the form even if I don't have the information for all of the current questions so that I can continue to make progress in the form when I can.

**Technical notes:**
* `required=False`
* Let's handle the likely user story in a future ticket by saving that part of validation for a summary screen or another near-the-end-of-the-process moment.

**Comment by kategarklavs** [comment]
@fureigh I'm happy to work on this next week, if a content perspective is needed 🎉

**Comment by fureigh** [comment]
@kategarklavs I think at the moment it's just a matter of unblocking the user. If you feel otherwise, though, feel free to propose changes to PR #74 (or file a new one)!

**Comment by fureigh** [comment]
(Ready for review in #74.)

**Comment by kategarklavs** [comment]
Sounds good!
