### ISSUE TITLE
Implement backup plans for user testing

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#69]
As we are conducting in-home user testing, there is a chance we are unable to access the alpha prototype/Cloze testing scripts.  

To prepare for that eventuality we need to:

- Ensure someone from each group can run the prototype locally
- Have paper printouts of the Cloze tests.

**Comment by fureigh** [comment]
@porta Do we need to have paper printouts or would PDFs (or screenshots or another on-screen approach) suffice?

Prototype running instructions are in the README. Best to allow some time for installing any dependencies that might come up.

**Comment by fureigh** [comment]
(^ @porta-antiporta, that is. Apologies to @porta.)

**Comment by kategarklavs** [comment]
@fureigh Printouts for the highlighter test copy/cloze test copy would be best! (In fact, the highlighter test might work better with printouts than it would onscreen.)
