### ISSUE TITLE
Identify agency users to interview and schedule

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#7]
The following folks are people who have been listed as good folks to get introductions
- Randy Hart/Omid Ghaffari-Tabrizi (FEMA - HUD acq stack project) connections to folks at Census at HUD that have wrangled with exchange of information and privacy
  - Anna O'Hara
  - PO for HUD
- Laura Godfrey - OPP Connections at multiple agencies
- Vicky McFadden
- Joel Minton - login.gov

Contact all the above and look to line up interview slots.
Should we create a 1-pager on what our project is looking to deliver in preparation for introductions to agency contacts?

**Comment by porta-antiporta** [comment]
Reached out to Omid from acqstack to have PO and deputy secretary (names redacted from GH comment) from HUD meet with us.  They have been the primary wranglers on the agency sharing that resulted in the CMA between HUD and FEMA.  Should know in a few days if we can schedule for our research.

Omid has a phone convo scheduled for Monday 10/24 to gauge his interest in participating; also looking to see if I can get an intro when he's in the Chicago office on Wednesday.

**Comment by porta-antiporta** [comment]
Meeting with Joel Minton on Monday to talk login.gov and how they approached agencies.

**Comment by porta-antiporta** [comment]
moving to this doc https://docs.google.com/document/d/1JpV6-tOug-jsEbn7FaiMSXhszmLFtoMU12QzbgygQXA/edit

**Comment by fureigh** [comment]
@porta-antiporta Safe to close this?

**Comment by porta-antiporta** [comment]
and 20 days later....
