### ISSUE TITLE
create hypotheses to be validated for prototype 2

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#91]
Based off our approach for our second prototype [here](https://gsa-tts.slack.com/archives/ffd-info-exchange/p1479850397002987).

Let's create our hypotheses for this second prototype.

Note: we need not define _how_ those hypotheses will be tested as part of this story, unless we feel we need to at this point.

Update the wiki to call out this information.

**Comment by fureigh** [comment]
I believe @kategarklavs added these to https://github.com/18F/ffd-info-exchange/wiki/Test-cases-and-hypotheses. Notes on which hypotheses we're testing in the next few weeks are [here](https://docs.google.com/document/d/11VvgpgJofKa_wHda1M5nKxV7i3yTNCgKtAsJNjPtxnw/edit).

**Comment by kategarklavs** [comment]
@porta-antiporta On Wednesday (after our meeting), I updated a few of our hypotheses in the original hypotheses/test cases doc in the wiki — would you like me to make a separate document highlighting only our second batch of hypotheses? (Happy to do so: just want to make sure I'm on the same page as everyone else.)

**Comment by porta-antiporta** [comment]
@kategarklavs could we call out in which we tested in round 1 and which in round 2?  (whether on the same wiki or separate i'm shruggie)

**Comment by kategarklavs** [comment]
@porta-antiporta Yep — I was planning to publish our Round 1 research results (informal doc) today, so I can add a bit about the specific hypotheses we tested!

**Comment by kategarklavs** [comment]
@porta-antiporta Round 1 research summary is up on the wiki! (And I added to the doc a list of hypotheses we tested in round 1.)

**Comment by kategarklavs** [comment]
Going through our issues, I saw that this one is still open (oops!). I added our round 2 hypotheses to the wiki on 12/9 — closing this issue now.
