### ISSUE TITLE
summarize sprint 3

### ISSUE THREAD

**Issue by porta-antiporta** [18F/ffd-info-exchange#92]
Let's summarize our sprint 3 and update the wiki.

**Comment by kategarklavs** [comment]
This is in progress! I'll have a draft to share w/the team shortly, and I'll be able to publish the final summary either EOD today or early tomorrow, depending on how quickly folks offer feedback.

**Comment by kategarklavs** [comment]
Shared draft document w/the team. I'll incorporate their feedback and will plan to publish the summary no later than EOD tomorrow.

**Comment by kategarklavs** [comment]
Forgot to close out this issue last week — I added the sprint 3 summary to our wiki before leaving last Wednesday!
