### ISSUE TITLE
Scaffold out mockup of USCIS workflow

### ISSUE THREAD

**Issue by fureigh** [18F/ffd-info-exchange#93]
The intent is to have a USCIS-consistent foundation to use as a starting point for recommending other possible services.

We have PDFs of six steps, some of which include up to a dozen possible options. I'll start somewhere and we can iterate from there.

**Comment by kategarklavs** [comment]
@fureigh Howdy! Is this foundation based on myUSCIS or a specific form offered by USCIS? Also, is now a good time to address content, or would it make more sense to hold off for a bit? (Happy to hop on a call today if you like — just let me know.)

**Comment by fureigh** [comment]
@kategarklavs It's currently based on the `PDFs for PRA Sept 30` mockups @donjo shared last week, which are for the N-400 (Application for Naturalization). Do you have thoughts on which ones to use or whether to follow a different direction?

**Comment by kategarklavs** [comment]
@fureigh N-400 works for me! (If I remember correctly, that's the most commonly used application track.) I'll check out the PDFs shortly 👍

**Comment by fureigh** [comment]
Closed in #95. Further development will take place in new issues.
